blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/Stonks-Life-Inc/.github/discussions
    about: Join the general discussion! We talk about everything and anything.
